### ISSUE TITLE
brave-* jars need updating to 3.10.0

### ISSUE THREAD

**Issue by samoverton** [thelastpickle/cassandra-zipkin-tracing#1]
Currently the code is compiled against 3.10.0 but the project is distributing 3.5.0 in the lib/ folder which means naively following the install instructions leads to runtime errors.

**Comment by samoverton** [comment]
On that subject, it seems that runtime also needs zipkin-1.7.0.jar which might be worth either distributing in lib/ or adding instructions to installation docs on where to obtain.

**Comment by michaelsembwever** [comment]
Thanks @samoverton for the reminder on this.

It has been fixed in the `cassandra-3.9` branch, but there was some delay getting it out. It was finally released yesterday. I will merge `cassandra-3.9`.
