### ISSUE TITLE
How to configure different IP/Port for Zipkin

### ISSUE THREAD

**Issue by kavink** [thelastpickle/cassandra-zipkin-tracing#4]
I could not see in readme how to point to a different IP/Port for Zipkin ? Please can you point me to an example ?

**Comment by michaelsembwever** [comment]
Edit these two lines: https://github.com/thelastpickle/cassandra-zipkin-tracing/blob/master/src/main/java/com/thelastpickle/cassandra/tracing/ZipkinTracing.java#L54-L55
