### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by samoverton** [thelastpickle/cassandra-zipkin-tracing#5]
This project doesn't seem to contain a license, and I'm unable to find any mention of the licensing of the code anywhere on github or on thelastpickle.com

Could you please add a license file, or some indication of the terms that the code is released under?

Thanks!

**Comment by zznate** [comment]
HI @samoverton - thanks for pointing this out. Corp. policy is ASFv2.0 on shared open source projects. I see no reason why this would not be shared in that category. Will get it sorted soon regardless.

**Comment by michaelsembwever** [comment]
done. thanks for pointing it out @samoverton
