### ISSUE TITLE
İnstallation cassandra-zipkin-tracing

### ISSUE THREAD

**Issue by ynsdl** [thelastpickle/cassandra-zipkin-tracing#9]
Hi,

I try to install cassandra-zipkin-tracing. I installed cassandra-zipkin-tracing and copied jars to cassandra lib directory.

edit cassandra-env.sh for JVM_OPTS and added -Dcassandra.custom_tracing_class=com.thelastpickle.cassandra.tracing.ZipkinTracing

if [ "$LOCAL_JMX" = "yes" ]; then
  JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.local.port=$JMX_PORT -Dcassandra.custom_tracing_class=com.thelastpickle.cassandra.tracing.ZipkinTracing"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
else
  JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.remote.port=$JMX_PORT -Dcassandra.custom_tracing_class=com.thelastpickle.cassandra.tracing.ZipkinTracing"

I started cassandra process but I cant see port 9411 inside LISTEN PORTS so http://127.0.0.1:9411/ cant reach here ? whats wrong?

**Comment by michaelsembwever** [comment]
If `http://127.0.0.1:9411/` is intended to be the Zipkin server then that is a separate process (the Zipkin Server) that you must run separately.

This library is for the tracing instrumentation of an existing Cassandra infrastructure.
